version: 2

jobs:
  build:
    docker:
      - image: dreadnaught/builder
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          #TAG=0.1.$CIRCLE_BUILD_NUM
          #$(aws ecr get-login --no-include-email --region us-east-1)
          #docker build -t demo:$TAG .
          #docker tag demo:latest 863823149701.dkr.ecr.us-east-1.amazonaws.com/demo:latest
          #docker push 863823149701.dkr.ecr.us-east-1.amazonaws.com/demo:latest
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ circleci@laramie.io:~/test

workflows:
  version: 2
    build-and-test:
      jobs:
        - build
